## Importing on python packages
import pandas as pd
import json
import xlrd
import bs4
import requests
import sqlalchemy
import pydub
from google.cloud import bigquery
import os # Package is used to degugging 

##Changing directory 
retval = os.getcwd()
print ("Current working directory %s" % retval)
##os.chdir('\GitHub\hha-data-ingestion')
#fkdatadir = os.path.join('D:/GitHub/', 'hha-data-ingestion/data/fakepatientdata.xlsx')

## Section 1 - Converting excel file into dataframe
# The excel file was generated by myself and does not represent any real world counterpart
#fkdata = xlrd.open_workbook('/Users/xxxda/Documents/GitHub/hha-data-ingestion/data/fakepatientdata.xls', on_demand=True)
#print(fkdata.sheet_names())

#tab1 = pd.read_excel('/Users/xxxda/Documents/GitHub/hha-data-ingestion/data/fakepatientdata.xls', sheet_name="Sheet1")
#tab2 = pd.read_excel('/Users/xxxda/Documents/GitHub/hha-data-ingestion/data/fakepatientdata.xls', sheet_name="Sheet2")

#print(tab1)
#print(tab2)

#########Code below is for main desktop
dfkdata = xlrd.open_workbook('D:/GitHub/hha-data-ingestion/data/fakepatientdata.xls', on_demand=True)
print(dfkdata.sheet_names())
dtab1 = pd.read_excel('/GitHub/hha-data-ingestion/data/fakepatientdata.xls', sheet_name="Sheet1")
dtab2 = pd.read_excel('/GitHub/hha-data-ingestion/data/fakepatientdata.xls', sheet_name="Sheet2")
print(dtab1)
print(dtab2)

##Section 2 - Use the requests package to open a json API via CMS
coviddata = requests.get('https://data.cms.gov/data-api/v1/dataset/1a52430d-febb-458d-9691-4d38a64c376d/data')
coviddata = coviddata.json()

##Section 3 - Pull 2 open source bigquery datasets; limiting to the first 100 rows as a dataframe
client = bigquery.Client.from_service_account_json('D:\GitHub\hha-data-ingestion\daniel-507-4cbcd50c9eb6.json')
##First Dataset
query_data1 = client.query("*SELECT *  FROM `patents-public-data.google_patents_research.publications` LIMIT 100")
dataresults1 = query_data1.results()

bigquery1 = pd.DataFrame(dataresults1.to_datadframe())

##Second Dataset
query_data2 = client.query("*SELECT * FROM `bigquery-public-data.faa.us_airports` LIMIT 100")
dataresults2 = query_data2.results()

bigquery2 = pd.DataFrame(dataresults2.to_dataframe())


print("Finished Running")